### PR TITLE
Core Community Services file addition + Fixes

### PR DESCRIPTION
**Pull request by stellardynamic**
We have so many tools and service now I think we need separate pages with lots of data.

### CODE REVIEW

**Comment by Gr33nDrag0n69** [comment]
I find it kind of odd that you remove my mainnet explorer to add yours.

Also why removing my mainnet snapshots servers and MrV one ? There are currently the most up to date and reliable with Isabella's one.

**Comment by Gr33nDrag0n69** [comment]
For the explorer, I don't really care since now there is a pletoria of them. (lisknode one was the only alternative for months). But for the snapshots I don't understand.

**Comment by stellardynamic** [comment]
You had no mainnet explorer there @Gr33nDrag0n as you can see Here
<https://github.com/LiskHQ/lisk-wiki/blob/master/Community%20Resources.md>.
Both of your links were from testnet services. This list is meant to
include as many as possiuble  so please add yours or send me the info so I
can add your services.

https://github.com/LiskHQ/lisk-wiki/blob/master/Community%20Resources.md

**Comment by Gr33nDrag0n69** [comment]
Sent all infos in lisk chat. Thanxs for fast answer.

**Comment by redsn0w0** [comment]
Thanks @stellardynamic

**Pull request merged**
